### PR TITLE
Some adds

### PR DESCRIPTION
**Pull request by dreamforceinc**
Commit c5515f6272a74d2c8d6f5a6c4277864a5dc4116f for issue #72
Commit 4b11e2a96125f8eb9244a7e444ab05ef0d84c948 for issue #74 and partially #63

### CODE REVIEW

**Comment by dreamforceinc** [comment]
Commit 12c90ca19c834aee5dd3753a79a3563cb2a2ffce for issue #63

**Review by benbuck — COMMENTED** [review]
Hi @dreamforceinc,

Would you mind please explaining the change in behavior from the minimize prior to hiding change?

Thanks,
Benbuck

**Comment by dreamforceinc** [comment]
> Would you mind please explaining the change in behavior from the minimize prior to hiding change?

[As @coderb sayd](https://github.com/benbuck/rbtray/issues/72), some child windows are not hidden after the "sw_hide" message, but are hidden if the message "sw_minimize" is sent first, and then "sw_hide". I checked, and it was confirmed, at least in the "Google Earth Pro". I don't know why this is happening, but it works. :)

**Comment by benbuck** [comment]
Hi @dreamforceinc,

Thanks for the changes, and sorry it's taken me so long to respond.

I'd prefer not to merge all of these at once. Would you mind please separating them out into a separate pull request for each logical change? Specifically:

1. Minimize prior to hiding
2. Add no-repeat flag to hotkey
3. Restore all feature

For that last one, the new hotkey is a bit of a complication since the biggest problem with the RBTray utility right now is that the hotkey has conflicts with other things in the system, so I think it would be better to add the restore all feature first in one pull request before adding another hotkey. Feel free to leave the documentation change for this feature to me if you like.

Thanks,
Benbuck

**Comment by benbuck** [comment]
Hi @dreamforceinc,

I also meant to ask about the problem with Total Commander that you discussed in issue #72, did you figure out how to avoid that?

Thanks,
Benbuck

**Pull request closed without merging**
